### PR TITLE
Add log in npy reader

### PR DESCRIPTION
**Pull request by ian-wazowski**
- Fixed npy reader to output a log if header is not of the correct type when performing a read.
- Fixed error in DataPtr, AlignedArray len() func

### CODE REVIEW

**Comment by nkaz001** [comment]
Regarding `len`, I'm unsure if it needs to be dereferenced. What error occurs?
https://doc.rust-lang.org/std/primitive.pointer.html#impl-*mut+%5BT%5D

**Comment by bohblue2** [comment]
> Regarding `len`, I'm unsure if it needs to be dereferenced. What error occurs? https://doc.rust-lang.org/std/primitive.pointer.html#impl-*mut+%5BT%5D

Rust analyzer detected error.

is that can occurred due to cargo version ?
This error always happened on my laptops 20 commits ago

**Comment by bohblue2** [comment]
```
error[E0658]: use of unstable library feature 'slice_ptr_len'
   --> hftbacktest/src/utils/aligned.rs:103:22
    |
103 |             len: ptr.len(),
    |                      ^^^
    |
    = note: see issue #71146 <https://github.com/rust-lang/rust/issues/71146> for more information
```

```
error[E0658]: use of unstable library feature 'slice_ptr_len'
   --> hftbacktest/src/backtest/data/mod.rs:143:18
    |
143 |         self.ptr.len()
    |                  ^^^
    |
    = note: see issue #71146 <https://github.com/rust-lang/rust/issues/71146> for more information
```

I'm sure my cargo settings are wrong, but it would be nice to have some information about the unstable library feature in the README.md.

**Comment by bohblue2** [comment]
`rustup update` solve these problem, sorry for interrupt.

For reference, ian-wazowski is my account.

**Comment by nkaz001** [comment]
The minimum required Rust version has been added to Cargo.toml. [06afa17fcfc2d7b16d54d62ed6abf42930e5605a]

**Pull request merged**
