### PR TITLE
Avoid incomplete npz file when force end histfile conversion

### PR DESCRIPTION
**Pull request by WannabeBotter**
After my Bybit histdata utility is merged, I realized when I force stop the convert process, incomplete npz file may remain.
So I changed the utility so that it won't leave incomplete npz file.

### CODE REVIEW

**Comment by nkaz001** [comment]
Does that happen only if you force stop the process or an error occurs? If so, I don't think we need to handle that situation.

**Comment by WannabeBotter** [comment]
You are right. The issue occurs only when the user forcefully stops the conversion process. I found the issue when I convert many files into npz format from a script.

In such situation, there is a workaround to deal with the issue by removing the generated npz files with the latest timestamps.

**Comment by nkaz001** [comment]
A user needs to write at least a short Python script to convert the data using `convert` method. If a user needs to specifically handle such a situation, they should retrieve the data without `output_filename` argument and then process it as you described. In my opinion, the library function does not need to handle such situations internally.

**Comment by WannabeBotter** [comment]
Understood. Closing this pull request.

**Pull request closed without merging**
